# Generated by Django 5.1.4 on 2025-01-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(
                    choices=[
                        ('Banteay Meanchey', 'Banteay Meanchey'),
                        ('Battambang', 'Battambang'),
                        ('Kampong Cham', 'Kampong Cham'),
                        ('Kampong Chhnang', 'Kampong Chhnang'),
                        ('Kampong Speu', 'Kampong Speu'),
                        ('Kampong Thom', 'Kampong Thom'),
                        ('Kandal', 'Kandal'),
                        ('Kep', 'Kep'),
                        ('Koh Kong', 'Koh Kong'),
                        ('Kratie', 'Kratie'),
                        ('Mondulkiri', 'Mondulkiri'),
                        ('Phnom Penh', 'Phnom Penh'),
                        ('Preah Vihear', 'Preah Vihear'),
                        ('Prey Veng', 'Prey Veng'),
                        ('Pursat', 'Pursat'),
                        ('Ratanakiri', 'Ratanakiri'),
                        ('Siem Reap', 'Siem Reap'),
                        ('Sihanoukville', 'Sihanoukville'),
                        ('Stung Treng', 'Stung Treng'),
                        ('Svay Rieng', 'Svay Rieng'),
                        ('Takeo', 'Takeo'),
                        ('Tboung Khmum', 'Tboung Khmum'),
                    ],
                    max_length=100
                )),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]