# Generated by Django 5.1.4 on 2025-01-09 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CF', 'Coffee'), ('CB', 'Coffee Bean'), ('MSC', 'MilkShakeChocolate'), ('CFI', 'CoffeeFrapIce'), ('CO', 'Coffee'), ('IM', 'IceMocha'), ('CZ', 'Cheese'), ('IC', 'Ice-Coffee')], max_length=255),
        ),
    ]
