# Generated by Django 5.1.4 on 2025-01-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_user_alter_customer_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CF', 'Coffee'), ('CB', 'Coffee Bean'), ('MSC', 'MilkShakeChocolate'), ('CFI', 'CoffeeFrapIce'), ('CO', 'Cup'), ('IM', 'IceMocha'), ('CZ', 'Cheese'), ('IC', 'Ice-Coffee')], max_length=255),
        ),
    ]
