# Generated by Django 5.1.4 on 2025-01-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CF', 'Coffee'), ('CB', 'Coffee Bean'), ('MSC', 'MilkShakeChocolate'), ('CFI', 'CoffeeFrapIce'), ('CO', 'Cup'), ('IM', 'IceMocha'), ('CE', 'CupExtra'), ('IC', 'Ice-Coffee')], max_length=255),
        ),
    ]
